#include <iostream>
#include "week_2/prac2.cpp"

using namespace std;

// TODO:
// 1. Implement a switch menu and mapping of each weeks practicals and their tasks
//    to call at runtime.
// 2. Add doxygen or some autogenerated docs to output at runtime for each weeks
//    practical and their associated tasks e.g what the function does, what parameters
//    to pass etc.

int main()
{   
    // task 2.3
    // int a = 30;
    // int b = 20;
    // int c = 10;
    // 
    // sort(a, b, c);
    // 
    // cout << a << " " << b << " "<< c << endl;

    // task 2.4
    calculatePowerlineLength();

    return 0;
}