#include <iostream>
#include "week_3/prac3.cpp"

using namespace std;

/** TODO:
* 1. Implement a switch menu and mapping of each weeks practicals and their tasks
*    to call at runtime.
* 2. Add doxygen or some autogenerated docs to output at runtime for each weeks
*    practical and their associated tasks e.g what the function does, what parameters
*    to pass etc.
* 3. Refactor week_1 and week_2 modules so code blocks conform to modern c++ style guide.
**/

int main()
{   
    // task 3.1
    // task 3.2
    // task 3.3

    return 0;
}